Failure # 1 (occurred at 2021-07-18_01-35-45)
Traceback (most recent call last):
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 718, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 688, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/_private/client_mode_hook.py", line 62, in wrapper
    return func(*args, **kwargs)
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/worker.py", line 1496, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.

