Failure # 1 (occurred at 2021-06-29_02-09-13)
Traceback (most recent call last):
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 718, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 688, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/_private/client_mode_hook.py", line 62, in wrapper
    return func(*args, **kwargs)
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/worker.py", line 1494, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ValueError): [36mray::PPO.train_buffered()[39m (pid=12199, ip=192.168.0.106)
  File "python/ray/_raylet.pyx", line 501, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 451, in ray._raylet.execute_task.function_executor
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/_private/function_manager.py", line 563, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/tune/trainable.py", line 173, in train_buffered
    result = self.train()
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 608, in train
    raise e
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 594, in train
    result = Trainable.train(self)
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/tune/trainable.py", line 232, in train
    result = self.step()
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/rllib/agents/trainer_template.py", line 173, in step
    res = next(self.train_exec_impl)
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/util/iter.py", line 756, in __next__
    return next(self.built_iterator)
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/util/iter.py", line 791, in apply_foreach
    result = fn(item)
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/rllib/execution/train_ops.py", line 66, in __call__
    self.sgd_minibatch_size, [])
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/rllib/utils/sgd.py", line 119, in do_minibatch_sgd
    }, minibatch.count)))[policy_id]
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/rllib/evaluation/rollout_worker.py", line 921, in learn_on_batch
    info_out[pid] = policy.learn_on_batch(batch)
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/rllib/utils/threading.py", line 21, in wrapper
    return func(self, *a, **k)
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/rllib/policy/torch_policy.py", line 458, in learn_on_batch
    grads, fetches = self.compute_gradients(postprocessed_batch)
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/rllib/policy/policy_template.py", line 335, in compute_gradients
    return parent_cls.compute_gradients(self, batch)
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/rllib/utils/threading.py", line 21, in wrapper
    return func(self, *a, **k)
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/rllib/policy/torch_policy.py", line 509, in compute_gradients
    tower_outputs = self._multi_gpu_parallel_grad_calc(batches)
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/rllib/policy/torch_policy.py", line 853, in _multi_gpu_parallel_grad_calc
    raise last_result
ValueError: The parameter loc has invalid values
In tower 0 on device cuda:0

