[ERROR 2021-07-18 00:53:11,073] function_runner.py: 254  Runner Thread raised error.
Traceback (most recent call last):
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/tune/function_runner.py", line 248, in run
    self._entrypoint()
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/tune/function_runner.py", line 316, in entrypoint
    self._status_reporter.get_checkpoint())
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/tune/function_runner.py", line 580, in _trainable_func
    output = fn()
  File "train_selfplay.py", line 102, in selfplay_train_func
    result = pred_agent.train()
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 605, in train
    raise e
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 594, in train
    result = Trainable.train(self)
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/tune/trainable.py", line 232, in train
    result = self.step()
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/rllib/agents/trainer_template.py", line 173, in step
    res = next(self.train_exec_impl)
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/util/iter.py", line 756, in __next__
    return next(self.built_iterator)
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  [Previous line repeated 1 more time]
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/util/iter.py", line 876, in apply_flatten
    for item in it:
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/util/iter.py", line 828, in add_wait_hooks
    item = next(it)
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  [Previous line repeated 1 more time]
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/util/iter.py", line 471, in base_iterator
    yield ray.get(futures, timeout=timeout)
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/_private/client_mode_hook.py", line 62, in wrapper
    return func(*args, **kwargs)
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/worker.py", line 1494, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(TypeError): [36mray::RolloutWorker.par_iter_next()[39m (pid=17834, ip=10.91.54.72)
  File "python/ray/_raylet.pyx", line 501, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 451, in ray._raylet.execute_task.function_executor
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/_private/function_manager.py", line 563, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/util/iter.py", line 1151, in par_iter_next
    return next(self.local_it)
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/rllib/evaluation/rollout_worker.py", line 333, in gen_rollouts
    yield self.sample()
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/rllib/evaluation/rollout_worker.py", line 726, in sample
    batches = [self.input_reader.next()]
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 99, in next
    batches = [self.get_data()]
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 226, in get_data
    item = next(self.rollout_provider)
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 651, in _env_runner
    base_env.send_actions(actions_to_send)
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/rllib/env/base_env.py", line 363, in send_actions
    self.vector_env.vector_step(action_vector)
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/rllib/env/vector_env.py", line 167, in vector_step
    obs, r, done, info = self.envs[i].step(actions[i])
  File "/home/hany606/repos/research/Drones-PEG-Bachelor-Thesis-2022/2D/gym-predprey/gym_predprey/envs/PredPrey1v1.py", line 145, in step
    self._process_action(action)        # self.ac has changed
  File "/home/hany606/repos/research/Drones-PEG-Bachelor-Thesis-2022/2D/gym-predprey/gym_predprey/envs/PredPrey1v1.py", line 281, in _process_action
    PredPreyEvorobot._process_action(self, action)
  File "/home/hany606/repos/research/Drones-PEG-Bachelor-Thesis-2022/2D/gym-predprey/gym_predprey/envs/PredPrey1v1.py", line 125, in _process_action
    self.ac[2:] = self.prey_policy.compute_single_action(obs=self.ob)
TypeError: compute_single_action() missing 1 required positional argument: 'self'
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/tune/function_runner.py", line 267, in run
    raise e
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/tune/function_runner.py", line 248, in run
    self._entrypoint()
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/tune/function_runner.py", line 316, in entrypoint
    self._status_reporter.get_checkpoint())
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/tune/function_runner.py", line 580, in _trainable_func
    output = fn()
  File "train_selfplay.py", line 102, in selfplay_train_func
    result = pred_agent.train()
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 605, in train
    raise e
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 594, in train
    result = Trainable.train(self)
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/tune/trainable.py", line 232, in train
    result = self.step()
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/rllib/agents/trainer_template.py", line 173, in step
    res = next(self.train_exec_impl)
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/util/iter.py", line 756, in __next__
    return next(self.built_iterator)
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  [Previous line repeated 1 more time]
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/util/iter.py", line 876, in apply_flatten
    for item in it:
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/util/iter.py", line 828, in add_wait_hooks
    item = next(it)
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  [Previous line repeated 1 more time]
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/util/iter.py", line 471, in base_iterator
    yield ray.get(futures, timeout=timeout)
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/_private/client_mode_hook.py", line 62, in wrapper
    return func(*args, **kwargs)
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/worker.py", line 1494, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(TypeError): [36mray::RolloutWorker.par_iter_next()[39m (pid=17834, ip=10.91.54.72)
  File "python/ray/_raylet.pyx", line 501, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 451, in ray._raylet.execute_task.function_executor
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/_private/function_manager.py", line 563, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/util/iter.py", line 1151, in par_iter_next
    return next(self.local_it)
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/rllib/evaluation/rollout_worker.py", line 333, in gen_rollouts
    yield self.sample()
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/rllib/evaluation/rollout_worker.py", line 726, in sample
    batches = [self.input_reader.next()]
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 99, in next
    batches = [self.get_data()]
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 226, in get_data
    item = next(self.rollout_provider)
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 651, in _env_runner
    base_env.send_actions(actions_to_send)
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/rllib/env/base_env.py", line 363, in send_actions
    self.vector_env.vector_step(action_vector)
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/rllib/env/vector_env.py", line 167, in vector_step
    obs, r, done, info = self.envs[i].step(actions[i])
  File "/home/hany606/repos/research/Drones-PEG-Bachelor-Thesis-2022/2D/gym-predprey/gym_predprey/envs/PredPrey1v1.py", line 145, in step
    self._process_action(action)        # self.ac has changed
  File "/home/hany606/repos/research/Drones-PEG-Bachelor-Thesis-2022/2D/gym-predprey/gym_predprey/envs/PredPrey1v1.py", line 281, in _process_action
    PredPreyEvorobot._process_action(self, action)
  File "/home/hany606/repos/research/Drones-PEG-Bachelor-Thesis-2022/2D/gym-predprey/gym_predprey/envs/PredPrey1v1.py", line 125, in _process_action
    self.ac[2:] = self.prey_policy.compute_single_action(obs=self.ob)
TypeError: compute_single_action() missing 1 required positional argument: 'self'

