Failure # 1 (occurred at 2021-06-26_15-05-27)
Traceback (most recent call last):
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 718, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 688, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/_private/client_mode_hook.py", line 62, in wrapper
    return func(*args, **kwargs)
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/worker.py", line 1496, in get
    raise value
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, [36mray::PPO.__init__()[39m (pid=28077, ip=10.91.73.206)
  File "python/ray/_raylet.pyx", line 501, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 451, in ray._raylet.execute_task.function_executor
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/_private/function_manager.py", line 563, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/rllib/agents/trainer_template.py", line 123, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 548, in __init__
    super().__init__(config, logger_creator)
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/tune/trainable.py", line 98, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 709, in setup
    self._init(self.config, self.env_creator)
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/rllib/agents/trainer_template.py", line 155, in _init
    num_workers=self.config["num_workers"])
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 797, in _make_workers
    logdir=self.logdir)
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/rllib/evaluation/worker_set.py", line 83, in __init__
    lambda p, pid: (pid, p.observation_space, p.action_space)))
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/_private/client_mode_hook.py", line 62, in wrapper
    return func(*args, **kwargs)
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, [36mray::RolloutWorker.__init__()[39m (pid=28070, ip=10.91.73.206)
  File "python/ray/_raylet.pyx", line 501, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 451, in ray._raylet.execute_task.function_executor
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/_private/function_manager.py", line 563, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/rllib/evaluation/rollout_worker.py", line 537, in __init__
    policy_dict, policy_config)
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1196, in _build_policy_map
    policy_map[name] = cls(obs_space, act_space, merged_conf)
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/rllib/policy/policy_template.py", line 281, in __init__
    stats_fn=stats_fn,
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/rllib/policy/policy.py", line 623, in _initialize_loss_from_dummy_batch
    self._dummy_batch, explore=False)
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/rllib/policy/torch_policy.py", line 262, in compute_actions_from_input_dict
    seq_lens, explore, timestep)
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/rllib/utils/threading.py", line 21, in wrapper
    return func(self, *a, **k)
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/rllib/policy/torch_policy.py", line 326, in _compute_action_helper
    seq_lens)
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/rllib/models/modelv2.py", line 234, in __call__
    res = self.forward(restored, state or [], seq_lens)
  File "train_1v1_simple2.py", line 87, in forward
    seq_lens)
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/rllib/models/modelv2.py", line 224, in __call__
    input_dict["obs"], self.obs_space, self.framework)
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/rllib/models/modelv2.py", line 378, in restore_original_dimensions
    return _unpack_obs(obs, original_space, tensorlib=tensorlib)
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/rllib/models/modelv2.py", line 414, in _unpack_obs
    prep.shape[0], obs.shape))
ValueError: Expected flattened obs shape of [..., 6], got torch.Size([32, 2])

