Failure # 1 (occurred at 2021-06-07_16-44-57)
Traceback (most recent call last):
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 586, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 609, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/worker.py", line 1456, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RayOutOfMemoryError): [36mray::PPO.train_buffered()[39m (pid=18187, ip=192.168.0.107)
  File "python/ray/_raylet.pyx", line 480, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 432, in ray._raylet.execute_task.function_executor
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/tune/trainable.py", line 167, in train_buffered
    result = self.train()
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 526, in train
    raise e
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 515, in train
    result = Trainable.train(self)
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/tune/trainable.py", line 226, in train
    result = self.step()
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/rllib/agents/trainer_template.py", line 148, in step
    res = next(self.train_exec_impl)
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/util/iter.py", line 756, in __next__
    return next(self.built_iterator)
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  [Previous line repeated 1 more time]
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/util/iter.py", line 876, in apply_flatten
    for item in it:
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/util/iter.py", line 828, in add_wait_hooks
    item = next(it)
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  [Previous line repeated 1 more time]
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/util/iter.py", line 471, in base_iterator
    yield ray.get(futures, timeout=timeout)
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)
ray.exceptions.RayTaskError(RayOutOfMemoryError): [36mray::RolloutWorker.par_iter_next()[39m (pid=18178, ip=192.168.0.107)
  File "python/ray/_raylet.pyx", line 440, in ray._raylet.execute_task
  File "/home/hany606/.local/lib/python3.6/site-packages/ray/memory_monitor.py", line 132, in raise_if_low_memory
    self.error_threshold))
ray.memory_monitor.RayOutOfMemoryError: More than 95% of the memory on node hany606 is used (14.71 / 15.48 GB). The top 10 memory consumers are:

PID	MEM	COMMAND
18187	2.43GiB	ray::PPO.train_buffered()
18987	2.27GiB	/home/hany606/miniconda3/bin/python /home/hany606/miniconda3/bin/conda-env create -f environment.yml
6266	1.71GiB	/usr/share/code/code /home/hany606/.vscode/extensions/ms-python.vscode-pylance-2021.6.0/dist/server.
6409	0.63GiB	/home/hany606/.config/Code/User/globalStorage/tabnine.tabnine-vscode/binaries/3.4.25/x86_64-unknown-
3021	0.45GiB	/usr/bin/gnome-shell
6284	0.34GiB	/home/hany606/.config/Code/User/globalStorage/tabnine.tabnine-vscode/binaries/3.4.25/x86_64-unknown-
18055	0.28GiB	python3 trajtrack_agent.py
18185	0.28GiB	ray::RolloutWorker
18184	0.28GiB	ray::RolloutWorker
18182	0.28GiB	ray::RolloutWorker

In addition, up to 0.15 GiB of shared memory is currently being used by the Ray object store.
---
--- Tip: Use the `ray memory` command to list active objects in the cluster.
---

